### ISSUE TITLE
Afbeeldingen van hoge resolutie die een coach upload hebben een onjuiste oriëntatie

### ISSUE THREAD

**Issue by blackdragon234** [Ecodenl/Woningdossier#1782]
**Url van Hoom omgeving** 
https://valleienergie.hoomdossier.nl/

**Beschrijving:**
Als Coach kun je bij een Hoomdossier een "Woningfoto" uploaden bij het overzicht van de woning in admin/buildings/show/[id]. De originele foto wordt op de eerste pagina van het woonrapportage toegevoegd. Deze foto kwam er 90 graden counterclockwise in terecht. Toen ik de resolutie van de foto sterk verlaagde kwam de foto wel met de juiste oriëntatie terecht.

**Stappen om te reproduceren**
Stappen om het gedrag te reproduceren:

Ga naar het admin dashboard.
Navigeer naar een Hoomdossier die aan je als Coach is toegewezen.
Upload een woningfoto van hoge resolutie (>3MP)
Maak een woonrapportage en dan stond de foto gekanteld op de eerste pagina afgebeeld.
Verwachting was uiteraard dat de foto op de correcte manier geörienteerd was.

**Schermafbeeldingen**
Indien van toepassing, voeg schermafbeeldingen toe om je probleem uit te leggen.

**Besturingssysteem:** Windows 10. De coach die de melding bracht gebruikt volgens mij MacOS
**Browser:** Alleen in Chrome getest.

**Aanvullende context**
De originele foto was 3000 x 4000 pixels (erg groot) en was met ,jpg kwaliteitscompression (Windows Photos app) onder de 1MB upload limiet gebracht. Eerst had ik de foto gehalveerd (1500 x 2000), maar deze kwam ook gekanteld op de voorpagina.
De foto die wel met de juiste oriëntatie werd afgebeeld in de rapportage was uiteindelijk 900 x 1200 pixels.
Bijgevoegd zijn de twee foto's:
![Originele foto](https://github.com/user-attachments/assets/8196e91d-220d-46b9-9588-4bf8a01b350b)
![IMG_20240531_112207 laag kleiner formaat](https://github.com/user-attachments/assets/28a16c1d-60d8-4b0d-8605-cfae77515ca3)

Ik heb ook de twee woonrapportages, maar daar staan mijn eigen adresgegevens in.... Mochten die gewenst zijn, mail dan naar arno.vandrenth@energiesamenfoodvalley.nl

**Comment by johannesfrolich** [comment]
Ik heb even zitten testen, met deze twee afbeeldingen gaat het idd mis, maar ik probeerde het ook met andere foto's die ik verkleind heb en daarbij ging het wel goed. Ook bij foto's met grote afmetingen 3000 x 4000 pixels. Ik heb even in de informatie van jouw foto's gekeken (die samen met de foto zijn opgeslagen) en daarbij valt op dat bij 'Richting' '90 graden linksom geroteerd' staat. Het lijkt iets in de instellingen van het programma waarmee de eerste foto is verkleind (onder de limiet van 1 mb gebracht). Bij de tweede foto staat hierbij 'normaal'.
<img width="401" alt="Scherm­afbeelding 2024-10-01 om 16 36 23" src="https://github.com/user-attachments/assets/4c179b22-3b45-433f-94bd-4a7442efc80c">
<img width="456" alt="Scherm­afbeelding 2024-10-01 om 16 36 32" src="https://github.com/user-attachments/assets/f7a83a2f-ca30-4f0f-83e8-6acf287e0961">
Misschien kun jij ook nog een keer met een andere foto proberen?

**Comment by blackdragon234** [comment]
Dit bevestigd eigenlijk wat ik in de eerste plaats had verwacht, dat ergens in de metadata van de foto was opgeslagen wat de oriëntatie van de foto is. Ik kon zelf in windows eigenschappen, de foto's app en een paar andere bestandsbewerkingsprogramma's niks zien qua oriëntatiedata, maar in pdfviewer van macos staat het er blijkbaar wel bij. 

Dan weet ik alleen niet helemaal waarom bij de 2e keer halveren de metadata wel was aangepast terwijl bij de eerste halvering het niet gebeurde, maar dat is niet echt het issue hier. 
Andere foto's werken wel gewoon naar behoren. Wellicht is dan wel een punt voor de toekomst om te kijken of bij het genereren van een rapportage deze metadata van een foto ook niet genegeerd kan worden. Op die manier zou het dit issue waarschijnlijk moeten voorkomen.
